import { Inter } from "@next/font/google";
import "../styles/global.css";
import styles from "./styles.module.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Next.js Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className={styles.container}>
        <Header />
        <main> {children} </main>
        <Footer />
      </body>
    </html>
  );
}
